
import Products from '@/components/home/Products';
import Loading from './loading';
import React, { Suspense } from 'react';

export const metadata = {
  title: "ALL PRODUCTS",
  description: "Generated by create next app",
};

const page = () => {
    return (
        <div>
            <Suspense fallback={<Loading />}>
                <Products />
            </Suspense>
        </div>
    );
};

export default page;